name: h5ai
on:
  repository_dispatch:
    types: [h5ai]
  schedule:
    - cron: 0 0 * * 0,3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #- name: WeChat notification #微信推送
      #run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=H5ai-开始构建
    - name: TG notification #TG推送
      run: curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=H5ai-开始构建"
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: bin20088/h5ai:1.19.8
    #- name: WeChat notification #微信推送
      #run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=H5ai推送成功-构建结束
    - name: TG notification #TG推送
      run: curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=H5ai推送成功-构建结束"
